/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.penguinapple.nb.lista.de.tareas;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import mx.penguinapple.nb.lista.de.tareas.SQLiteDatabase;

/**
 *
 * @author Reindhart
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form ULogin
     */
    public Login() {
        setUndecorated(true);
        initComponents();
        lblErrorMsg.setVisible(false);
        Image img = new ImageIcon(getClass().getResource("/img/wia_img_check-0.png")).getImage();
        this.setIconImage(img);        
    }
    
    public static void slp(JLabel label) {
        new Thread(() -> {
            try {
                Thread.sleep(3000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
            SwingUtilities.invokeLater(() -> label.setVisible(false));
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblPwd = new javax.swing.JLabel();
        btnAccept = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        lblLogin = new javax.swing.JLabel();
        lblErrorMsg = new javax.swing.JLabel();
        lblSingIn = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUser.setText("Usuario");
        jPanel2.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        lblPwd.setText("Contraseña");
        jPanel2.add(lblPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        btnAccept.setText("Aceptar");
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        jPanel2.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 190, -1));
        jPanel2.add(pwdPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 190, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogin.setText("INICIA SESIÓN");
        jPanel2.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        lblErrorMsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorMsg.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMsg.setText("mensaje");
        jPanel2.add(lblErrorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 310, -1));

        lblSingIn.setForeground(new java.awt.Color(51, 0, 255));
        lblSingIn.setText("Registrate aquí");
        lblSingIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSingIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSingInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSingInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSingInMouseExited(evt);
            }
        });
        jPanel2.add(lblSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 450, 350));

        btnExit.setBackground(new java.awt.Color(204, 204, 204));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/msg_error-0.png")));
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        JTextField username = txtUser;
        JPasswordField password = pwdPassword;
        JLabel errorMsg = lblErrorMsg;
        
        if(username.getText().isBlank() || password.getPassword().length == 0){
            errorMsg.setText("Porfavor rellene ambos campos");
            errorMsg.setVisible(true);
            slp(lblErrorMsg);
        }
        
        String[] user = SQLiteDatabase.searchUser(username.getText(), password.getPassword());
        if (user != null){
            Tareas tareas = new Tareas(user);
            tareas.setVisible(true);
            dispose();
        } else {
            errorMsg.setText("Usuario o contraseña incorrectos");
            errorMsg.setVisible(true);
            slp(lblErrorMsg);
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void lblSingInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSingInMouseEntered
        this.setForeground(new Color(0, 0, 153));
    }//GEN-LAST:event_lblSingInMouseEntered

    private void lblSingInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSingInMouseExited
        this.setForeground(new Color(51, 0, 255));
    }//GEN-LAST:event_lblSingInMouseExited

    private void lblSingInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSingInMouseClicked
        JFrame singin = new SignIn();
        singin.setVisible(true);
    }//GEN-LAST:event_lblSingInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnExit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPwd;
    private javax.swing.JLabel lblSingIn;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
