/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.penguinapple.nb.lista.de.tareas;

import com.github.lgooddatepicker.components.DatePickerSettings;
import java.time.LocalDate;

/**
 *
 * @author Reindhart
 */
public class NewTask extends javax.swing.JFrame {
    
    private final String nameGroup;
    private final int idGroup;
    private DatePickerSettings dateSettings = new DatePickerSettings();
    private LocalDate today = LocalDate.now();
    
    public NewTask(Grupo group) {
        this.nameGroup = group.getNombre();
        this.idGroup = group.getId();
        initComponents();
        this.setTitle("Tarea para " + this.nameGroup);
        dateSettings.setDateRangeLimits(today, null);
        
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDescription = new javax.swing.JLabel();
        lblDueDate = new javax.swing.JLabel();
        btnCancelTask = new javax.swing.JButton();
        btnAcceptTask = new javax.swing.JButton();
        txtDescription = new javax.swing.JTextField();
        dtpDueDateTime = new com.github.lgooddatepicker.components.DateTimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nueva Tarea");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescription.setText("Descripción");
        jPanel1.add(lblDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblDueDate.setText("Fecha limite");
        jPanel1.add(lblDueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        btnCancelTask.setText("Cancelar");
        btnCancelTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelTaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        btnAcceptTask.setText("Aceptar");
        btnAcceptTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptTaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcceptTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));
        jPanel1.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, -1));
        jPanel1.add(dtpDueDateTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelTaskActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelTaskActionPerformed

    private void btnAcceptTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptTaskActionPerformed

    }//GEN-LAST:event_btnAcceptTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        int id = 1; String nombre = "Cositas";
        Grupo test = new Grupo(id, nombre);
        
        java.awt.EventQueue.invokeLater(() -> new NewTask(test).setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptTask;
    private javax.swing.JButton btnCancelTask;
    private com.github.lgooddatepicker.components.DateTimePicker dtpDueDateTime;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDueDate;
    private javax.swing.JTextField txtDescription;
    // End of variables declaration//GEN-END:variables
}
