/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.penguinapple.nb.lista.de.tareas;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import static mx.penguinapple.nb.lista.de.tareas.SQLiteDatabase.insertarUsuario;
import static mx.penguinapple.nb.lista.de.tareas.Login.slp;
/**
 *
 * @author Reindhart
 */
public class SignIn extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignIn.class.getName());

    /**
     * Creates new form SignIn
     */
    public SignIn() {
        setUndecorated(true);
        initComponents();
        this.lblErrorMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtUserSingIn = new javax.swing.JTextField();
        btnAcceptSingIn = new javax.swing.JButton();
        btnCLoseSingIn = new javax.swing.JButton();
        lblUserSignIn = new javax.swing.JLabel();
        lblPasswordSingIn = new javax.swing.JLabel();
        lblErrorMsg = new javax.swing.JLabel();
        pwdPasswordSingIn = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUserSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserSingInActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 210, -1));

        btnAcceptSingIn.setText("Aceptar");
        btnAcceptSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptSingInActionPerformed(evt);
            }
        });
        jPanel1.add(btnAcceptSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, -1));

        btnCLoseSingIn.setText("X");
        btnCLoseSingIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCLoseSingInActionPerformed(evt);
            }
        });
        jPanel1.add(btnCLoseSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 30, -1));

        lblUserSignIn.setText("Usuario");
        jPanel1.add(lblUserSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblPasswordSingIn.setText("Contraseña");
        jPanel1.add(lblPasswordSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        lblErrorMsg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblErrorMsg.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorMsg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMsg.setText("mensaje");
        jPanel1.add(lblErrorMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 320, -1));
        jPanel1.add(pwdPasswordSingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, -1));

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserSingInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserSingInActionPerformed

    private void btnAcceptSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptSingInActionPerformed
        
        JLabel errorMsg = this.lblErrorMsg;
        JTextField user = this.txtUserSingIn;
        JPasswordField pass = this.pwdPasswordSingIn;
        
        if(user.getText().isBlank() || pass.getPassword().length == 0){
            errorMsg.setText("Porfavor llene ambos campos");
            errorMsg.setVisible(true);
            user.setText("");
            pass.setText("");
            slp(errorMsg);
        }
        if(!insertarUsuario(user.getText(), pass.getPassword())){
            errorMsg.setText("El usuario ya existe");
            errorMsg.setVisible(true);
            user.setText("");
            pass.setText("");
            slp(errorMsg);
        }
    }//GEN-LAST:event_btnAcceptSingInActionPerformed

    private void btnCLoseSingInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCLoseSingInActionPerformed
        dispose();
    }//GEN-LAST:event_btnCLoseSingInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignIn().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcceptSingIn;
    private javax.swing.JButton btnCLoseSingIn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblErrorMsg;
    private javax.swing.JLabel lblPasswordSingIn;
    private javax.swing.JLabel lblUserSignIn;
    private javax.swing.JPasswordField pwdPasswordSingIn;
    private javax.swing.JTextField txtUserSingIn;
    // End of variables declaration//GEN-END:variables
}
