/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.penguinapple.nb.lista.de.tareas;
import java.awt.Component;
import mx.penguinapple.nb.lista.de.tareas.Grupo;

import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
/**
 *
 * @author Reindhart
 */
public class Tareas extends javax.swing.JFrame {
    
    private final String[] userData;
    private  DefaultTableModel tableModel;
    private Grupo lastSelectedValue;

    /**
     * Creates new form Tareas
     * @param userData
     */
    public Tareas(String[] userData) {        
        
        tableModel = new DefaultTableModel(new Object[]{""}, 0);
        
        initComponents();
        
        this.userData = userData;
        lblUser.setText(userData[1]);
        
        this.setTitle("Tareas de " + userData[1]);
        Image img = new ImageIcon(getClass().getResource("/img/wia_img_check-0.png")).getImage();
        this.setIconImage(img);
        
        tblToDoList.getColumnModel().getColumn(0).setPreferredWidth(0);
        loadGroups(userData);        
        
        btnAddTask.setEnabled(false);
        btnAddTask.setVisible(false);
        btnDeleteGroup.setEnabled(false);
        btnDeleteGroup.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnAddTask = new javax.swing.JButton();
        lblGroups = new javax.swing.JLabel();
        lblTasks = new javax.swing.JLabel();
        spGroupList = new javax.swing.JScrollPane();
        lstGroupList = new javax.swing.JList<>();
        spToDoList = new javax.swing.JScrollPane();
        tblToDoList = new javax.swing.JTable();
        lblUser = new javax.swing.JLabel();
        btnAddGroup = new javax.swing.JButton();
        btnDeleteGroup = new javax.swing.JButton();
        btnDeleteCompleted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddTask.setText("Nueva Tarea");
        btnAddTask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, -1, -1));

        lblGroups.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGroups.setText("Grupos");
        jPanel1.add(lblGroups, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblTasks.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTasks.setText("Tareas");
        jPanel1.add(lblTasks, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        lstGroupList.setModel(new DefaultListModel<Grupo>());
        lstGroupList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstGroupListMouseClicked(evt);
            }
        });
        spGroupList.setViewportView(lstGroupList);

        jPanel1.add(spGroupList, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 120, 370));

        spToDoList.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spToDoListPropertyChange(evt);
            }
        });

        tblToDoList.setModel(this.tableModel);
        tblToDoList.setColumnSelectionAllowed(true);
        spToDoList.setViewportView(tblToDoList);
        tblToDoList.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(spToDoList, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 660, 370));

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUser.setText("Usuario");
        lblUser.setToolTipText("");
        jPanel1.add(lblUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 360, -1));

        btnAddGroup.setText("Nuevo Grupo");
        btnAddGroup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGroupActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        btnDeleteGroup.setText("Borrar Grupo");
        btnDeleteGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGroupActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        btnDeleteCompleted.setText("Eliminar Completados");
        btnDeleteCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCompletedActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        JFrame newtask = new NewTask(lastSelectedValue, tableModel);
        newtask.setVisible(true);
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnAddGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGroupActionPerformed
        String groupName = JOptionPane.showInputDialog("Escriba el nombre del grupo");
        
        DefaultListModel<Grupo> model = (DefaultListModel<Grupo>) lstGroupList.getModel();
        
        if (model == null){
            model = new DefaultListModel<>();
            lstGroupList.setModel(model);
        }        
        
        int id = SQLiteDatabase.addGroup(userData[0], groupName);
        Grupo nuevoGrupo = new Grupo(id, groupName);
        model.addElement(nuevoGrupo); 

        JOptionPane.showMessageDialog(null, "Se ha guardado correctamente el grupo");
    }//GEN-LAST:event_btnAddGroupActionPerformed

    private void lstGroupListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGroupListMouseClicked
        
        lastSelectedValue = lstGroupList.getSelectedValue();
        String currentValue = lstGroupList.getSelectedValue().getNombre();
        if(!currentValue.isBlank()){
            btnAddTask.setEnabled(true); 
            btnAddTask.setVisible(true);
            btnDeleteGroup.setEnabled(true);            
            btnDeleteGroup.setVisible(true);
            loadTasks(lastSelectedValue.getId());
        }
    }//GEN-LAST:event_lstGroupListMouseClicked

    private void btnDeleteGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGroupActionPerformed
        
        DefaultListModel model = (DefaultListModel) lstGroupList.getModel();
        
        int delete = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar: " + lastSelectedValue + "?", "Eliminar Grupo", JOptionPane.YES_NO_OPTION);
        if (delete == JOptionPane.OK_OPTION){
            if (SQLiteDatabase.deleteGroup(lastSelectedValue.getId())){
                
                JOptionPane.showMessageDialog(null, "Se ha borrado el grupo");                
                
                int item = lstGroupList.getSelectedIndex();
                model.remove(item);
                
                tableModel.setRowCount(0);
            }
        }
    }//GEN-LAST:event_btnDeleteGroupActionPerformed

    private void btnDeleteCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCompletedActionPerformed
        final int rowCount = tableModel.getRowCount();
        final int idCol = 0; 
        final int completedCol = 1;
        List<Integer> completedTasks = new ArrayList<>();
        List<Integer> rows = new ArrayList<>();
        
        for (int row = 0; row < rowCount; row++){
            Object idValue = tableModel.getValueAt(row, idCol);
            Object completedTask = tableModel.getValueAt(row, completedCol);
            
            if(completedTask.equals(true)){
                rows.add(row);
                completedTasks.add((Integer) idValue);
            }
        }
        if (completedTasks.isEmpty()){
            JOptionPane.showConfirmDialog(rootPane, "No hay tareas por eliminar");
            return;
        }
        
        if (SQLiteDatabase.deletTasks(completedTasks)){
            for (int row : rows){
                tableModel.removeRow(row);
            }
            JOptionPane.showMessageDialog(null, "Se han eliminado las tareas completadas");
        }
    }//GEN-LAST:event_btnDeleteCompletedActionPerformed

    private void spToDoListPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spToDoListPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spToDoListPropertyChange

    private void resizeColsWidth(JTable table){
        
        final int idColIndex = 0, completedColIndex = 1, dueDateColIndex = 3;
        TableColumnModel colModel = table.getColumnModel();
        
        // Id Column
        TableColumn idColModel = colModel.getColumn(idColIndex);
        idColModel.setMinWidth(0);
        idColModel.setMaxWidth(0);
        idColModel.setPreferredWidth(0);                       
        
        //Completed Column
        TableColumn completedCol = colModel.getColumn(completedColIndex);
        TableCellRenderer completedRenderer = completedCol.getHeaderRenderer();
        if (completedRenderer == null) {
            completedRenderer = table.getTableHeader().getDefaultRenderer();
        }
        Component completedComponent = completedRenderer.getTableCellRendererComponent(table, completedCol.getHeaderValue(), false, false, -1, completedColIndex);
        int completedWidth = completedComponent.getPreferredSize().width + 10;
        completedCol.setMinWidth(completedWidth);
        completedCol.setMaxWidth(completedWidth);
        completedCol.setPreferredWidth(completedWidth);
        
        // Description Column
        table.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
        
        // Due Date Column
        TableColumn dueDateCol = colModel.getColumn(dueDateColIndex);
        int maxDueDateWidth = 0;
        
        for(int row = 0; row < table.getRowCount(); row++){
            TableCellRenderer dueDateRenderer = table.getCellRenderer(row, dueDateColIndex);
            Component dueDateComponent = table.prepareRenderer(dueDateRenderer, row, dueDateColIndex);
            maxDueDateWidth = Math.max(dueDateComponent.getPreferredSize().width, maxDueDateWidth);
        }        
        maxDueDateWidth += 10;
        dueDateCol.setMaxWidth(maxDueDateWidth);
        dueDateCol.setPreferredWidth(maxDueDateWidth);
    }
    
    private void loadGroups(String[] userData){
        DefaultListModel<Grupo> grupos = SQLiteDatabase.getGroups(userData);
        if (!grupos.isEmpty()){
            lstGroupList.setModel(grupos);
        }
    }
    
    private void loadTasks(int id){
        tableModel = SQLiteDatabase.getTasks(id);
        
        if(tableModel != null){
            tblToDoList.setModel(tableModel);
            resizeColsWidth(tblToDoList);
            tblToDoList.setRowHeight(25);
            
            tblToDoList.getModel().addTableModelListener(new TableModelListener() {
                @Override
                public void tableChanged(TableModelEvent e) {
                    int type = e.getType();
                    int column = e.getColumn();
                    int row = e.getFirstRow();
                    int idCol = 0, completedCol = 1;

                    if (type == TableModelEvent.UPDATE && column == completedCol) {
                        Boolean newValue = (Boolean) tableModel.getValueAt(row, column);

                        int id = (int) tableModel.getValueAt(row, idCol);                        
                        SQLiteDatabase.completTask(id, newValue);
                    }
                }
            });
        }
    }
    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGroup;
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnDeleteCompleted;
    private javax.swing.JButton btnDeleteGroup;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblGroups;
    private javax.swing.JLabel lblTasks;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<Grupo> lstGroupList;
    private javax.swing.JScrollPane spGroupList;
    private javax.swing.JScrollPane spToDoList;
    private javax.swing.JTable tblToDoList;
    // End of variables declaration//GEN-END:variables
}
